In [1]:
import numpy as np

# アレイを作る

In [4]:
my_list = [1,2,3,4]

In [3]:
my_array1 = np.array(my_list)
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [11,22,33,44]

In [6]:
my_lists = [my_list, my_list2]
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [8]:
my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [9]:
my_array2.shape

(2, 4)

In [10]:
my_array2.dtype

dtype('int64')

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
my_zeros = np.zeros(5)

In [13]:
my_zeros.dtype

dtype('float64')

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.ones(5,5)

TypeError: data type not understood

In [16]:
np.empty((3,4))

array([[-2.31584178e+077,  1.49458025e-154,  2.19235555e-314,
         2.19238497e-314],
       [ 2.19238500e-314,  2.19239068e-314,  2.19239104e-314,
         2.19238504e-314],
       [ 2.19239136e-314,  2.19238511e-314,  2.19238483e-314,
         8.34404889e-309]])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

# アレイを使った計算

In [20]:
5/2

2.5

In [21]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [22]:
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [23]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [25]:
arr1 ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

# アレイの添字

In [27]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[8]

8

In [29]:
arr[1:5]

array([1, 2, 3, 4])

In [30]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [31]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [32]:
arr = np.arange(0,11)

In [33]:
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [34]:
slice_arr[:] = 99
slice_arr

array([99, 99, 99, 99, 99, 99])

In [35]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### ※アレイのスライスは参照

<br />

In [37]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [38]:
arr_copy[:] = 55
arr_copy

array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55])

In [39]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [40]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [41]:
arr_2d[1]

array([20, 25, 30])

In [42]:
arr_2d[1][0]

20

In [43]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [44]:
arr_2d[2]

array([35, 40, 45])

In [45]:
arr_2d[2,:]

array([35, 40, 45])

In [47]:
arr_2d = np.zeros((10,10))
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [51]:
arr_length = arr_2d.shape[0]
arr_length

10

In [52]:
for i in range(arr_length):
    arr_2d[i] = i
    
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [53]:
arr_2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [54]:
arr_2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])